import './globals.css'
import Header from '../components/old/Header'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
      <Header />
      <main>{children}</main>
      </body>
    </html>
  )
}
